/**
 * file: Question3_4.java.
 * author: Alex Antaki
 * course: CMPT 220
 * assignment: Lab 2
 * due date: February 8, 2017
 * version: 1
 *
 * This file generates a random number and assigns the number to the proper
  month.  For example, 1 is January.
 */

public class Question3_4 {
  public static void main(String[] args) {

    //This double takes a random number from 1 to 12 and is generated randomly.
    double month = (int)(Math.random() * 12) + 1;

    //This if takes the random number generated by the computer and corresponds
    //it to the month and displays the name of the month.
    if(month == 1)
      System.out.println("January");
    else if(month == 2)
      System.out.println("February");
    else if(month == 3)
      System.out.println("March");
    else if(month == 4)
      System.out.println("April");
    else if(month == 5)
      System.out.println("May");
    else if(month == 6)
      System.out.println("June");
    else if(month == 7)
      System.out.println("July");
    else if(month == 8)
      System.out.println("August");
    else if(month == 9)
      System.out.println("September");
    else if(month == 10)
      System.out.println("October");
    else if(month == 11)
      System.out.println("November");
    else
      System.out.println("December");
  }
}
